// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7CA_uWzggZUx-TTvEFYEYoG6q7iDSO3s',
    appId: '1:465500664688:web:fe2c1e05d311673e3d95b5',
    messagingSenderId: '465500664688',
    projectId: 'e-commerce-7a067',
    authDomain: 'e-commerce-7a067.firebaseapp.com',
    storageBucket: 'e-commerce-7a067.appspot.com',
    measurementId: 'G-0WGLDJ03FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9y13VzWmfSajB9zbMnEZAtDx0tzrviPE',
    appId: '1:465500664688:android:d993abbc9f28108c3d95b5',
    messagingSenderId: '465500664688',
    projectId: 'e-commerce-7a067',
    storageBucket: 'e-commerce-7a067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDubTEQeX_fATZQNdYdPmWHp_jxeDle-6o',
    appId: '1:465500664688:ios:d5f1197f2bf436ad3d95b5',
    messagingSenderId: '465500664688',
    projectId: 'e-commerce-7a067',
    storageBucket: 'e-commerce-7a067.appspot.com',
    iosClientId: '465500664688-148k72smls33sj862k3j70n5d6i1s0if.apps.googleusercontent.com',
    iosBundleId: 'com.nadeer.growMark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDubTEQeX_fATZQNdYdPmWHp_jxeDle-6o',
    appId: '1:465500664688:ios:d5f1197f2bf436ad3d95b5',
    messagingSenderId: '465500664688',
    projectId: 'e-commerce-7a067',
    storageBucket: 'e-commerce-7a067.appspot.com',
    iosClientId: '465500664688-148k72smls33sj862k3j70n5d6i1s0if.apps.googleusercontent.com',
    iosBundleId: 'com.nadeer.growMark',
  );
}
